image: node:8-alpine

before_script:
  - cp -R /root/DataCenterUI/node_modules /builds/dayucloud/DataCenterUI/
  - npm config set registry https://registry.npm.taobao.org/
  - npm install

stages:
  - build

build:
  stage: build
  only:
    - master
  script:
    - npm run build
    - rm -rf /root/DataCenterUI/dist/js
    - rm -rf /root/DataCenterUI/dist/css
    - cp -R /builds/dayucloud/DataCenterUI/dist /root/DataCenterUI/
    - sed -i 's/localhost\:5000/112.124.3.134\:8300/g' /root/DataCenterUI/dist/js/app.*.js