image: node:8-alpine

before_script:
  - npm config set registry https://registry.npm.taobao.org/
  - npm install

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  only:
    - master
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 20min

deploy:
  stage: deploy
  services:
    - docker:stable-dind
  image: docker:stable
  script:
    - docker info