image: node:8-alpine

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - npm config set registry https://registry.npm.taobao.org/
    - npm install
  script:
    - npm run test

build:
  stage: build
  only:
    - master
  before_script:
    - npm config set registry https://registry.npm.taobao.org/
    - npm install
  script:
    - npm run build
    - cp Dockerfile dist/
    #- rm -rf /root/xxx/xxx/*
    #- cp -R dist/* /root/xxx/xxx
  artifacts:
    paths:
      - dist
    expire_in: 20min

deploy:
  stage: deploy
  only:
    - release
  services:
    - docker:stable-dind # gitlab runner 配置中的 privileged 要设置为 true
  image: docker:stable
  script:
    - cd dist
    # docker仓库，tag等信息根据实际项目调整。
    - docker login -u $DOCKER_USER -p $DOCKER_PWD registry.cn-hangzhou.aliyuncs.com 
    - docker build -t registry.cn-hangzhou.aliyuncs.com/jmax/xxx:v$(cat version) .
    - docker push registry.cn-hangzhou.aliyuncs.com/jmax/xxx:v$(cat version)