image: node:8-alpine

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - npm config set registry https://registry.npm.taobao.org/
    - npm install
  script:
    - npm run test

build:
  stage: build
  only:
    - master
  before_script:
    - npm config set registry https://registry.npm.taobao.org/
    - npm install
  script:
    - npm run build
    - cp Dockerfile dist/
  artifacts:
    paths:
      - dist
    expire_in: 20min

deploy:
  stage: deploy
  services:
    - docker:stable-dind # gitlab runner 配置中的 privileged 要设置为 true
  image: docker:stable
  script:
    - docker info
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION .
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION